### PR TITLE
Bump Go to 1.19 and Gardener to 1.62

### PR DESCRIPTION
**Pull request by elchead**
How to categorize this PR?

/area security
/kind technical-debt

What this PR does / why we need it:
update to Go 1.19
upgrade to Gardener 1.62

Replace the removed `TryUpdate` with `GetAndCreateOrMergePatch` as suggested here:
https://github.com/gardener/gardener/blob/v1.62.2/docs/development/kubernetes-clients.md#on-helper-functions

Replaced the removed `EnsureFinalizer` with `AddFinalizers` as suggested by the similar function description.

Fix the unit tests

Which issue(s) this PR fixes:
Fixes #

Special notes for your reviewer:

Release note:
```
update to Go 1.19
upgrade to Gardener 1.62
```

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @elchead for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by MartinWeindel — COMMENTED** [review]
Verify now fails at lint, this is an adhoc error fix

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
