### PR TITLE
Remove steps for integration tests in pipeline

### PR DESCRIPTION
**Pull request by MartinWeindel**
**How to categorize this PR?**

/area delivery
/kind cleanup
/platform azure

**What this PR does / why we need it**:
The outdated `tm-test` script is not supported anymore. The new token-based script is not allowed to be run on the external, public concourse. The remedy integration test has been moved to the internal concourse at https://concourse.ci.gardener.cloud.sap/teams/gardener-dev/pipelines/landscape-dev-tests-master/jobs/master-manual-remedy-controller-test-job

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Moved integration test to internal CI because of security constraints
```

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
This PR proposes changes that would break the pipeline definition:
```
remedy-controller-remove-test-steps: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/concourse/replicator.py", line 140, in render
    definition_descriptor = self._render(definition_descriptor)
  File "/usr/lib/python3.10/site-packages/concourse/replicator.py", line 223, in _render
    raise RuntimeError(
RuntimeError: An exception occured when rendering pipeline 'remedy-controller-remove-test-steps': 

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/concourse/replicator.py", line 215, in _render
    definition_descriptor.pipeline = t.render(
  File "/usr/lib/python3.10/site-packages/mako/template.py", line 439, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 874, in _render
    _render_context(
  File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 916, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 943, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7f1dd2a48e80", line 661, in render_body
    ${job(variant)}
  File "memory:0x7f1dd2a48e80", line 0, in job
    
  File "memory:0x7f1dd2a48e80", line 649, in render_job
    ${step(4, job_variant, job_variant.step(step_name))}
  File "/usr/lib/python3.10/site-packages/concourse/model/job.py", line 248, in step
    raise ValueError(f'no such step: {name=}')
ValueError: no such step: name='test'


```

**Comment by gardener-robot-ci-2** [comment]
The pipeline-definition has been fixed.

**Review by kon-angelo — APPROVED** [review]
/lgtm

**Pull request merged**
